# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /var/www/modelmesh.cloud/ssl/config/archive/modelmesh.cloud
cert = /var/www/modelmesh.cloud/ssl/config/live/modelmesh.cloud/cert.pem
privkey = /var/www/modelmesh.cloud/ssl/config/live/modelmesh.cloud/privkey.pem
chain = /var/www/modelmesh.cloud/ssl/config/live/modelmesh.cloud/chain.pem
fullchain = /var/www/modelmesh.cloud/ssl/config/live/modelmesh.cloud/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = e98714a7fb8f4aff66d25db0b87795be
config_dir = /var/www/modelmesh.cloud/ssl/config
work_dir = /var/www/modelmesh.cloud/ssl/work
logs_dir = /var/www/modelmesh.cloud/ssl/logs
authenticator = webroot
webroot_path = /var/www/modelmesh.cloud,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
modelmesh.cloud = /var/www/modelmesh.cloud
www.modelmesh.cloud = /var/www/modelmesh.cloud
