# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /var/www/truenorthinsurancesolutions.com/ssl/config/archive/truenorthinsurancesolutions.com
cert = /var/www/truenorthinsurancesolutions.com/ssl/config/live/truenorthinsurancesolutions.com/cert.pem
privkey = /var/www/truenorthinsurancesolutions.com/ssl/config/live/truenorthinsurancesolutions.com/privkey.pem
chain = /var/www/truenorthinsurancesolutions.com/ssl/config/live/truenorthinsurancesolutions.com/chain.pem
fullchain = /var/www/truenorthinsurancesolutions.com/ssl/config/live/truenorthinsurancesolutions.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 2b2feac8e035cde9f28a093a6158a98e
config_dir = /var/www/truenorthinsurancesolutions.com/ssl/config
work_dir = /var/www/truenorthinsurancesolutions.com/ssl/work
logs_dir = /var/www/truenorthinsurancesolutions.com/ssl/logs
authenticator = webroot
webroot_path = /var/www/truenorthinsurancesolutions.com,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
truenorthinsurancesolutions.com = /var/www/truenorthinsurancesolutions.com
www.truenorthinsurancesolutions.com = /var/www/truenorthinsurancesolutions.com
